"""Checks the roadmap schema cannot express: ID uniqueness, resolvable edges, acyclicity, existing files.

Writes roadmap/TreeTask.md, a generated index the Conductor reads instead of opening every
document. Never edit that file by hand.

Usage: python3 check_roadmap.py <roadmap_dir> [schema.json] [--no-index]
"""

import json
import pathlib
import re
import sys

import jsonschema

ID = re.compile(r"^[A-Z][A-Z0-9]*-[0-9]{2,}$")


def walk(doc_path, doc_dir, node, docs, entries, edges, files):
    """Collect where each node id is declared.

    A node appears once as a document (when it has its own file) and once as a
    child entry in its parent, so an id declared in two parents, or as two
    documents, is the real defect.
    """
    docs.setdefault(node["id"], []).append(str(doc_path))
    for child in node.get("tasks", []):
        child_id = child["id"]
        edges.append((node["id"], child_id))
        entries.setdefault(child_id, []).append(str(doc_path))
        for dep in child.get("blockedBy", []):
            edges.append((child_id, dep))
        if child.get("file"):
            files.append((doc_path, child_id, doc_dir / child["file"]))


PHASE_ORDER = ["proposal", "spec", "design", "task", "apply", "verify", "archive"]
STATUS_ICON = {
    "draft": "·", "ready": "o", "blocked": "!", "inProgress": ">",
    "paused": "=", "completed": "x", "canceled": "-",
}


NODE_DOCS = {"specs.md", "tests.md", "traceability.md", "design.md", "verify.md"}


def check_refs(root, nodes, problems):
    """ref.design entries resolve in one of two ways: a bare name matching one of this
    node's own documents, which survives archiving because it travels with the node; or a
    path relative to the project root. A bare name that is neither is a reference that
    nothing will ever resolve."""
    for rel, doc in nodes.items():
        entries = list(doc.get("ref", {}).get("design", []))
        for child in doc.get("tasks", []):
            entries.extend(child.get("ref", {}).get("design", []))
        for entry in entries:
            if "/" in entry:
                target = entry.split("#", 1)[0]
                if not (root / target).exists():
                    problems.append(f"{rel}: ref.design points at a missing file: {target}")
                continue
            name = entry.split("#", 1)[0]
            if name not in NODE_DOCS:
                problems.append(
                    f"{rel}: ref.design '{entry}' is neither one of this node's documents "
                    f"({', '.join(sorted(NODE_DOCS))}) nor a path"
                )


def render_index(root, docs):
    """TreeTask.md: one line per node, deepest phase first, so the Conductor can
    read the project's state without opening every document."""
    rows = []
    # keyed by absolute path, since the caller walks from main.json's location
    by_file = {rel.resolve(): doc for rel, doc in docs.items()}

    def visit(abs_path, doc):
        children = doc.get("tasks", [])
        for child in children:
            child_path = abs_path.parent / child["file"] if child.get("file") else None
            child_doc = by_file.get(child_path.resolve()) if child_path else None
            if child_doc:
                visit(child_path, child_doc)
        phase = doc.get("phase")
        rows.append({
            "id": doc["id"],
            "level": doc["level"],
            "status": doc["status"],
            "phase": phase or "—",
            "name": doc["name"],
            "path": str(abs_path.relative_to(root)),
            "open": len(doc.get("openQuestions", [])),
            "blockers": ", ".join(doc.get("blockedBy", [])) or "—",
            "children": len(children),
        })

    main_path = next((p for p in docs if docs[p].get("level") == "main"), None)
    if main_path:
        visit(main_path, docs[main_path])

    out = [
        "# TreeTask",
        "",
        "Generated by `check_roadmap.py`. Do not edit: change the JSON and re-run.",
        "",
        "Legend: status `o` ready, `>` inProgress, `!` blocked, `·` draft, `x` completed.",
        "Phase `—` means the node spans stages or its stage is undecided.",
        "",
        "| ID | Level | Status | Phase | Open | Name | Blocked by | Path |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for r in rows:
        out.append(
            f"| {r['id']} | {r['level']} | {STATUS_ICON.get(r['status'], '?')} {r['status']} "
            f"| {r['phase']} | {r['open']} | {r['name']} | {r['blockers']} | `{r['path']}` |"
        )

    out += ["", "## Frontier", ""]
    leaves = []
    for rel, doc in docs.items():
        kids = doc.get("tasks", [])
        if not kids:
            continue
        for c in kids:
            if not c.get("file"):
                leaves.append((doc["id"], c))
    ready = [(p, c) for p, c in leaves
             if c["status"] == "ready" and not c.get("blockedBy")]
    blocked = [(p, c) for p, c in leaves if c["status"] == "ready" and c.get("blockedBy")]
    if ready:
        out.append("Startable now, no unresolved blockers:")
        out += [f"- **{c['id']}** {c.get('whatToBuild') or c['name']}" for _, c in ready]
    else:
        out.append("No task is startable: every leaf either has blockers or is not ready.")
    if blocked:
        out += ["", "Ready but waiting on another task:", ""]
        out += [f"- **{c['id']}** {c['name']} (blocked by {', '.join(c['blockedBy'])})"
                for _, c in blocked]

    out += ["", "## By phase", ""]
    for phase in PHASE_ORDER:
        inphase = [r for r in rows if r["phase"] == phase]
        if inphase:
            out.append(f"**{phase}** — {', '.join(r['id'] for r in inphase)}")
    unphased = [r for r in rows if r["phase"] == "—"]
    if unphased:
        out += ["", f"**Undecided** — {', '.join(r['id'] for r in unphased)}"]

    out += ["", "## Open questions", ""]
    any_q = False
    for rel, doc in sorted(docs.items()):
        for q in doc.get("openQuestions", []):
            any_q = True
            out.append(f"- **{doc['id']}**: {q}")
    if not any_q:
        out.append("None.")
    out.append("")
    return "\n".join(out)


def main(roadmap_dir, schema_path, write_index=True):
    root = pathlib.Path(roadmap_dir)
    schema = json.loads(pathlib.Path(schema_path).read_text())
    validator = jsonschema.Draft202012Validator(schema)

    failures = []
    nodes = {}
    for path in sorted(root.rglob("*.json")):
        if path.name == schema_path.split("/")[-1]:
            continue
        doc = json.loads(path.read_text())
        errors = sorted(validator.iter_errors(doc), key=lambda e: list(e.absolute_path))
        for e in errors:
            where = "/".join(str(p) for p in e.absolute_path) or "<root>"
            failures.append(f"{path}: schema: {where}: {e.message}")
        nodes[path] = doc

    docs, entries, edges, files = {}, {}, [], []
    for path, doc in nodes.items():
        walk(path.relative_to(root), path.parent, doc, docs, entries, edges, files)

    for node_id, where in docs.items():
        if len(where) > 1:
            failures.append(f"duplicate document id {node_id}: {where}")

    for node_id, where in entries.items():
        if len(where) > 1:
            failures.append(f"id {node_id} declared in two parents: {where}")

    # every id, document or leaf, is a legal edge endpoint
    known = set(docs) | set(entries)

    for src, dst in edges:
        if dst not in known:
            failures.append(f"unresolved edge {src} -> {dst}")

    # acyclicity over blockedBy, which is the graph that schedules work
    blocked = {}
    for path, doc in nodes.items():
        for child in doc.get("tasks", []):
            blocked.setdefault(child["id"], set()).update(child.get("blockedBy", []))

    state = {}

    def visit(n, stack):
        if state.get(n) == "done":
            return
        if state.get(n) == "open":
            failures.append("cycle: " + " -> ".join(stack + [n]))
            return
        state[n] = "open"
        for dep in blocked.get(n, ()):
            if dep in blocked:
                visit(dep, stack + [n])
        state[n] = "done"

    for n in blocked:
        visit(n, [])

    for parent, child_id, target in files:
        if not target.exists():
            failures.append(f"{child_id} declared file not found: {target.relative_to(root)}")

    check_refs(root, nodes, failures)

    index = render_index(root, nodes)
    index_path = root / "TreeTask.md"
    if write_index:
        if not failures:
            index_path.write_text(index)
        print(f"wrote {index_path.relative_to(pathlib.Path.cwd()) if index_path.is_absolute() and index_path.is_relative_to(pathlib.Path.cwd()) else index_path}")

    print(f"{len(nodes)} documents, {len(docs)} ids, {len(edges)} edges")
    if failures:
        print("\nFAIL")
        for f in failures:
            print(f"  {f}")
        return 1
    print("OK: schema valid, ids unique, edges resolvable, acyclic, files exist")
    return 0


if __name__ == "__main__":
    args = [a for a in sys.argv[1:] if a != "--no-index"]
    raise SystemExit(main(
        args[0],
        args[1] if len(args) > 1 else
        str(pathlib.Path(__file__).resolve().parents[1] / "schema" / "roadmap.schema.json"),
        write_index="--no-index" not in sys.argv[1:],
    ))